### ISSUE TITLE
[RFE] Provide a way to get raw JSON body for List method

### ISSUE THREAD

**Issue by djberg96** [openshift-online/ocm-sdk-go#569]
Currently we have some code that looks something like this:

```
statuses := openapiStatusBoard.StatusList{}
err := json.Unmarshal(response.Bytes(), &statuses) // Bytes() is just the body
```

Unmarshalling a json response into a struct seems to be a popular idiom in Golang and it's convenient. However, it's not currently possible without using a raw HTTP GET method, somewhat defeating the nice API you've given us.

What I would like is the ability to do something like this:

```
response, _ := connection.StatusBoard().V1().Products().List().SendContext(ctx)
fmt.Println(response.Body())
```

**Comment by djberg96** [comment]
@jhernand Is this feasible?

**Comment by jhernand** [comment]
It is more complicated than it looks. The SDK deserializes the JSON stream directly into the response object:

https://github.com/openshift-online/ocm-sdk-go/blob/e89d6168db077ea7cadc83677ea755698bc40468/statusboard/v1/products_client.go#L354

https://github.com/openshift-online/ocm-sdk-go/blob/e89d6168db077ea7cadc83677ea755698bc40468/statusboard/v1/products_resource_json.go#L75-L105

That consumes the response body before `SendContext` returns. To implement what you suggest we would need a mechanism to tell that `SendContext` that it should not consume the response body, so you can consume it yourself, something like this:

```go
response, _ := connection.StatusBoard().V1().Products().List().
        Raw(true). // <- This is what will be telling SendContext to not deserialize the body.
        SendContext(ctx)
```

We would need to change the code generator to implement this `Raw` method for all the request objects.

We will also need a method in the response object to get the raw response body. It can't in general be named `Body` as you suggest because many response objects (`Add` and `Update`, for example) already have a `Body` method. It could also be named `Raw`:

```go
raw := response.Raw()
```

So technically it is doable, like almost any thing. But I think doing that goes against the nature of these methods which are intended to avoid all that handling of JSON serialization and deserialization.

Can you elaborate a bit more why you want this and why the existing raw HTTP GET method isn't enough for your use case?

I imagine that you may want to be able to process response fields that aren't defined in the model. Is it impossible to define those fields that you need in the model?
